# version: 2
# updates:
#   - package-ecosystem: "github-actions"
#     directories:
#       - "/"
#       - "actual"
#       - "compare"
#       - "expected"
#       - "prepare"
#     open-pull-requests-limit: 10
#     schedule:
#       interval: 'daily'
#       time: '00:00'
#       timezone: 'Asia/Tokyo'
#     groups:
#       github-actions:
#         patterns:
#           - "actions/*"
#         update-types:
#           - "minor"
#           - "patch"
#   - package-ecosystem: "npm"
#     directory: "/"
#     schedule:
#       interval: "daily"
#       time: "00:00"
#       timezone: "Asia/Tokyo"
