name: "Expected VRT"

description: "Expected VRT is a utility action for visual regression testing."

author: "yorifuji"

branding:
  icon: code
  color: blue

inputs:
  expected-dir:
    description: "Expected directory"
    required: true
  expected-cache-key:
    description: "Cache key for expected"
    required: true

runs:
  using: composite
  steps:
    # expected

    - shell: bash
      run: |
        if [ -e .easy-vrt ]; then exit 1; fi
        mkdir .easy-vrt && mv ${{ inputs.expected-dir }} .easy-vrt/expected

    - uses: actions/cache/save@5a3ec84eff668545956fd18022155c47e93e2684 # v4.1.2
      with:
        path: .easy-vrt/expected
        key: reg-suit-cache-${{ inputs.expected-cache-key }}
