name: "Actual VRT"

description: "Actual VRT is a utility action for visual regression testing."

author: "yorifuji"

branding:
  icon: code
  color: blue

inputs:
  actual-dir:
    description: "Actual directory"
    required: true
  actual-cache-key:
    description: "Cache key for actual"
    required: true

runs:
  using: composite
  steps:
    - shell: bash
      run: |
        if [ -e .easy-vrt ]; then exit 1; fi
        mkdir .easy-vrt && mv ${{ inputs.actual-dir }} .easy-vrt/actual

    - uses: actions/cache/save@d4323d4df104b026a6aa633fdb11d772146be0bf # v4.1.2
      with:
        path: .easy-vrt/actual
        key: reg-suit-cache-${{ inputs.actual-cache-key }}
