name: Assign PR to author

run-name: Assign PR Author

on:
  pull_request:
    types: opened

jobs:
  pr-assign:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      repository-projects: read
    if: ${{ !contains(github.actor, '[bot]') }}
    timeout-minutes: 30
    steps:
      - env:
          GH_TOKEN: ${{ github.token }}
        run: gh pr edit ${{ github.event.number }} --add-assignee ${{ github.actor }} --repo ${{ github.repository }}
